/**
 * X (Twitter) URL Validation — anti-hallucination gate for transfer sources/posts.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THIS EXISTS
 * ─────────────────────────────────────────────────────────────────────────────
 * The TransferSource and TransferPost DB tables were seeded by
 * scripts/seed-realistic-transfers.ts with FABRICATED X URLs:
 *   - Journalist sources: synthetic snowflake IDs like "2059000000125056427"
 *     (generated by xUrl() helper, all sharing the "205900000012" prefix).
 *   - Fan posts: synthetic IDs like "7416444269138177598" (generated by
 *     sagaIdHash() helper) that decode to year 2066 — 40 years in the future.
 *
 * Clicking these links leads to X's "this page doesn't exist" 404 page,
 * which is a hallucination: we're presenting fake URLs as real citations.
 *
 * This utility validates X post URLs by decoding the Snowflake status ID
 * (the 64-bit ID encodes the post's creation timestamp). If the decoded
 * date is in the future, too old, or unparseable, the URL is fabricated
 * and the caller MUST NOT render it as a clickable link.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * SNOWFLAKE ID FORMAT
 * ─────────────────────────────────────────────────────────────────────────────
 * X's 64-bit status IDs are Snowflake IDs:
 *   - Top 42 bits: milliseconds since the Twitter epoch
 *     (Nov 4, 2010 01:42:54.657 UTC = 1288834974657 ms)
 *   - Next 10 bits: machine ID
 *   - Bottom 12 bits: sequence
 *
 * Decoding: timestampMs = (id >> 22) + 1288834974657
 *
 * Real X posts created in 2026 have IDs around 1.8-2.0 × 10^18, which decode
 * to dates in 2026. The seed data's IDs decode to impossible dates (2066,
 * or suspiciously clustered around the same millisecond), revealing them
 * as fabricated.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** Twitter/X Snowflake epoch: Nov 4, 2010 01:42:54.657 UTC */
const TWITTER_EPOCH_MS = 1288834974657

/** Real X post URL shape. */
const X_URL_RE = /^https:\/\/(?:x\.com|twitter\.com)\/[^/]+\/status\/(\d+)/i

/** Reject posts older than this (days). Transfer rumors stale after 1 year. */
const MAX_AGE_DAYS = 365

/** Reject posts dated more than 1 day in the future (clock skew tolerance). */
const FUTURE_TOLERANCE_MS = 24 * 60 * 60 * 1000

export interface XUrlValidation {
  /** True if the URL is a real, verifiable X post URL. */
  valid: boolean
  /** Why validation failed (when valid=false). */
  reason?: string
  /** The decoded post date, if the URL is a valid snowflake. */
  decodedDate?: Date
}

/**
 * Decode a Twitter/X Snowflake status ID into the post's creation Date.
 * Returns null if the ID is invalid or decodes to an impossible date.
 *
 * @example
 *   decodeSnowflakeDate('2059000000129807827') // → a 2026 date (realistic)
 *   decodeSnowflakeDate('7416444269138177598') // → 2066 date → null (future)
 */
export function decodeSnowflakeDate(statusId: string | number | bigint): Date | null {
  let id: bigint
  try {
    id = BigInt(statusId)
  } catch {
    return null
  }
  // Valid Snowflake IDs are > 2^22 (the timestamp bits must be non-zero)
  if (id < 1n << 22n) return null
  // Top 42 bits = ms since Twitter epoch
  const timestampMs = Number(id >> 22n) + TWITTER_EPOCH_MS
  // Guard against overflow / NaN
  if (!Number.isFinite(timestampMs)) return null
  const d = new Date(timestampMs)
  if (isNaN(d.getTime())) return null
  // Sanity check: must be after Twitter epoch
  if (d.getTime() < TWITTER_EPOCH_MS) return null
  return d
}

/**
 * Extract the numeric status ID from an x.com/twitter.com post URL.
 * Returns null if the URL doesn't match the expected pattern.
 */
export function extractStatusIdFromXUrl(url: string): string | null {
  const match = url.match(X_URL_RE)
  return match ? match[1] : null
}

/**
 * Validate an X (Twitter) post URL for anti-hallucination.
 *
 * A URL is `valid` only if ALL of:
 *   1. It matches the real X post URL shape: https://(x.com|twitter.com)/<handle>/status/<digits>
 *   2. The status ID is a valid Snowflake ID that decodes to a real Date.
 *   3. The decoded date is NOT in the future (beyond a 24h clock-skew tolerance).
 *   4. The decoded date is NOT older than MAX_AGE_DAYS (365 days).
 *
 * For non-X URLs (reddit.com, example.com, etc.), this returns `{ valid: false,
 * reason: 'not-an-x-url' }`. Callers that handle non-X URLs should do their
 * own validation; this function is specifically for X post URL gate-keeping.
 *
 * @example
 *   validateXPostUrl('https://x.com/FabrizioRomano/status/2059000000125056427')
 *     // → { valid: true, decodedDate: 2026-05-25T... } (realistic 2026 date)
 *
 *   validateXPostUrl('https://x.com/TransferOracle/status/7416444269138177598')
 *     // → { valid: false, reason: 'future-dated-snowflake' } (decodes to 2066)
 */
export function validateXPostUrl(url: string | null | undefined): XUrlValidation {
  if (!url || typeof url !== 'string' || url.trim() === '') {
    return { valid: false, reason: 'empty-url' }
  }

  const statusId = extractStatusIdFromXUrl(url)
  if (!statusId) {
    // Not an X post URL at all (could be reddit, web, etc.) — not necessarily
    // fabricated, but this validator is X-specific.
    return { valid: false, reason: 'not-an-x-url' }
  }

  const decodedDate = decodeSnowflakeDate(statusId)
  if (!decodedDate) {
    return { valid: false, reason: 'invalid-snowflake' }
  }

  const now = Date.now()
  const decodedMs = decodedDate.getTime()

  // Future check: a real post can't be dated in the future
  if (decodedMs > now + FUTURE_TOLERANCE_MS) {
    return {
      valid: false,
      reason: 'future-dated-snowflake',
      decodedDate,
    }
  }

  // Stale check: reject posts older than MAX_AGE_DAYS
  const ageMs = now - decodedMs
  if (ageMs > MAX_AGE_DAYS * 24 * 60 * 60 * 1000) {
    return {
      valid: false,
      reason: 'stale-snowflake',
      decodedDate,
    }
  }

  return { valid: true, decodedDate }
}

/**
 * Sanitize a URL for safe rendering: return the URL if it validates as a real
 * X post, otherwise return null. Callers should render the content WITHOUT a
 * clickable link when this returns null.
 *
 * For non-X URLs (reddit, web), this returns the URL unchanged — those are
 * validated separately by their own platform rules (or trusted at ingest).
 * Use `sanitizeXPostUrl` when you specifically need X post URL gate-keeping.
 *
 * @example
 *   const safeUrl = sanitizeXPostUrl(source.url)
 *   {safeUrl ? <a href={safeUrl}>...</a> : <div>...</div>}
 */
export function sanitizeXPostUrl(url: string | null | undefined): string | null {
  if (!url) return null
  // Non-X URLs pass through (not this validator's job)
  if (!X_URL_RE.test(url)) return url
  const result = validateXPostUrl(url)
  return result.valid ? url : null
}

/**
 * BATCH-LEVEL synthetic-URL detection.
 *
 * The seed script (scripts/seed-realistic-transfers.ts) generates journalist
 * source URLs with the `xUrl()` helper: `2059000000000000000 + seed*7919 +
 * 123456789`. These decode to plausible May-2026 dates, so per-URL snowflake
 * validation PASSES — but they're all fabricated (the tweets don't exist).
 *
 * The tell: they all share the 10-char snowflake prefix "2059000000". Real X
 * posts from different authors/days do NOT share a 10-char prefix. If a
 * majority of X post URLs in a batch share a 10-char status-ID prefix, the
 * whole batch is fabricated seed data.
 *
 * This function takes an array of URLs and returns a NEW array where:
 *   - X post URLs are null'd if the batch shows synthetic-prefix clustering
 *   - Non-X URLs (reddit, web) are preserved unchanged
 *   - X post URLs that individually fail snowflake validation are null'd
 *
 * @example
 *   const urls = sources.map(s => s.url)
 *   const safe = sanitizeXPostUrlBatch(urls)
 *   sources.forEach((s, i) => { s.url = safe[i] })
 */
export function sanitizeXPostUrlBatch(
  urls: (string | null | undefined)[],
): (string | null)[] {
  if (urls.length === 0) return []

  // First pass: per-URL validation
  const individuallyValid = urls.map((u) => {
    if (!u) return null
    if (!X_URL_RE.test(u)) return u // non-X URL — pass through
    return validateXPostUrl(u).valid ? u : null
  })

  // Second pass: batch-level synthetic-prefix clustering check
  // Collect the 10-char prefixes of all X post URLs that passed individual
  // validation. If any prefix appears in >50% of them, null them ALL out.
  const xUrlsWithPrefix: { idx: number; prefix: string }[] = []
  individuallyValid.forEach((u, idx) => {
    if (!u) return
    const statusId = extractStatusIdFromXUrl(u)
    if (!statusId || statusId.length < 10) return
    xUrlsWithPrefix.push({ idx, prefix: statusId.slice(0, 10) })
  })

  if (xUrlsWithPrefix.length >= 2) {
    const prefixCounts = new Map<string, number>()
    for (const { prefix } of xUrlsWithPrefix) {
      prefixCounts.set(prefix, (prefixCounts.get(prefix) ?? 0) + 1)
    }
    for (const [, count] of prefixCounts) {
      // If any single 10-char prefix covers >=50% of the X URLs, the batch
      // is synthetic (seed data). Null out ALL X URLs in the batch.
      if (count >= xUrlsWithPrefix.length / 2) {
        return individuallyValid.map((u) => {
          if (!u) return null
          // Null out X URLs, preserve non-X URLs
          return X_URL_RE.test(u) ? null : u
        })
      }
    }
  }

  return individuallyValid
}
